playbackControlsManagerUpdateTimerFired and m_playbackControlsManagerUpdateTimer must be guarded with ENABLE(VIDEO), otherwise the following error occurs with the VIDEO feature turned off:
  error: 'MediaElementSession' has not been declared

Add missing #if ENABLE(VIDEO) Page.cpp and Page.h
https://bugs.webkit.org/show_bug.cgi?id=189500

Patch by Pablo Saavedra <psaavedra@igalia.com> on 2018-09-11
Reviewed by Anders Carlsson.

* page/Page.cpp:
(WebCore::Page::Page):
(WebCore::Page::schedulePlaybackControlsManagerUpdate):
* page/Page.h:

git-svn-id: https://svn.webkit.org/repository/webkit/trunk@235895 268f45cc-cd09-0410-ab3c-d52691b4dbfc