WebStorageNamespaceProvider / StorageNamespaceImpl no longer need SessionIDs https://bugs.webkit.org/show_bug.cgi?id=201922 <rdar://problem/55505906>
Patch by Yury Semikhatsky <yurys@chromium.org> on 2019-09-19
Reviewed by Chris Dumez.

Fix GTK Debug compilation after https://trac.webkit.org/changeset/250083:
../../Source/WebKit/WebProcess/WebStorage/WebStorageNamespaceProvider.cpp:75:55: error: no member named 'singleton' in namespace 'WebCore::Process'
ASSERT_UNUSED(sessionID, sessionID == WebProcess::singleton().sessionID());
                                  ~~~~~~~~~~~~^

* WebProcess/WebStorage/WebStorageNamespaceProvider.cpp:

git-svn-id: https://svn.webkit.org/repository/webkit/trunk@250106 268f45cc-cd09-0410-ab3c-d52691b4dbfc