Build fix (r167151): Do not dereference Node::document() before passing to Range::create() <https://webkit.org/b/131475>
Fixes the following build failure:

    WebCore/editing/AlternativeTextController.cpp:275:71: error: indirection requires pointer operand ('WebCore::Document' invalid)
        int paragraphStartIndex = TextIterator::rangeLength(Range::create(*rootNode.document(), &rootNode, 0, paragraphRangeContainingCorrection.get()->startContainer(), paragraphRangeContainingCorrection.get()->startOffset()).get());
                                                                          ^~~~~~~~~~~~~~~~~~~~

* editing/AlternativeTextController.cpp:
(WebCore::AlternativeTextController::applyAlternativeTextToRange):
Remove unneeded '*' operator since Node::document() returns a
Document& and Range::create() accepts a Document& for its first
argument.

git-svn-id: https://svn.webkit.org/repository/webkit/trunk@167160 268f45cc-cd09-0410-ab3c-d52691b4dbfc