Unreviewed build fix for Windows ports
> WebKitBuild\Release\WTF\Headers\wtf/RefPtr.h(44): error C2027: use of undefined type 'WebCore::ImageData'

RefPtr<ImageData> is used without defining ImageData.

* platform/graphics/ConcreteImageBuffer.h: Added #include "ImageData.h".

git-svn-id: https://svn.webkit.org/repository/webkit/trunk@257130 268f45cc-cd09-0410-ab3c-d52691b4dbfc