Revert "BUILD FIX (r146558): Call [super dealloc] from -[TinyDOMNode dealloc]"
This fixes a build failure introduced by this change:

    Source/JavaScriptCore/API/tests/testapi.mm:206:6: error: ARC forbids explicit message send of 'dealloc'
        [super dealloc];
         ^     ~~~~~~~
    1 error generated.

Not sure why this didn't fail locally on my Mac Pro.

* API/tests/testapi.mm:
(-[TinyDOMNode dealloc]): Remove call to [super dealloc].

git-svn-id: https://svn.webkit.org/repository/webkit/trunk@146603 268f45cc-cd09-0410-ab3c-d52691b4dbfc