Reviewed by Richard
	Fix for this bug:

	Radar 3260323 (Some links at nike.com cause assertion failure
	(connectionDidFinishLoading sent after cancel))

	Added a flag which is set when a load is cancelled. This flag prevents
	bad behvior when loads that finish cause the load itself to be
	cancelled (which could happen with a javascript that changes the
	window location). This is used to prevent both the body of
	cancelWithError: and the body of connectionDidFinishLoading: running
	for a single delegate. Cancelling wins.

        * WebView.subproj/WebBaseResourceHandleDelegate.h:
        * WebView.subproj/WebBaseResourceHandleDelegate.m:
        (-[WebBaseResourceHandleDelegate connectionDidFinishLoading:]):
        (-[WebBaseResourceHandleDelegate cancelWithError:]):


git-svn-id: https://svn.webkit.org/repository/webkit/trunk@4443 268f45cc-cd09-0410-ab3c-d52691b4dbfc