Add validations for a synchronously constructed custom element https://bugs.webkit.org/show_bug.cgi?id=161528
Reviewed by Yusuke Suzuki.

Source/WebCore:

The latest DOM specification has sanity checks when creating an element with the synchronous custom elements flag set
in 6.1.3 through 10:
3. If result does not implement the HTMLElement interface, throw a TypeError.
4. If result's attribute list is not empty, then throw a NotSupportedError.
5. If result has children, then throw a NotSupportedError.
6. If result's parent is not null, then throw a NotSupportedError.
7. If result's node document is not document, then throw a NotSupportedError.
8. If result's namespace is not the HTML namespace, then throw a NotSupportedError.
9. If result's local name is not equal to localName, then throw a NotSupportedError.

Add all these checks to JSCustomElementInterface::constructElement.

Tests: fast/custom-elements/Document-createElement.html

* bindings/js/JSCustomElementInterface.cpp:
(WebCore::JSCustomElementInterface::constructElement): Report the exception thrown during parsing instead of just
clearing and ignoring it.
(WebCore::constructCustomElementSynchronously): Extracted out of constructElement so that we can also catch TypeError
and NotSupportedError we throw in constructElement for the parser.

LayoutTests:

Added test cases for sanity checks in step 6.1. of https://dom.spec.whatwg.org/#concept-create-element
and updated other test cases per those changes.

* fast/custom-elements/Document-createElement-expected.txt:
* fast/custom-elements/Document-createElement.html:
* fast/custom-elements/defined-pseudo-class-expected.txt: Rebaselined now that exceptions thrown while constructing
a custom element is reported in the console.
* fast/custom-elements/parser/parser-fallsback-to-unknown-element-expected.txt: Ditto.


git-svn-id: https://svn.webkit.org/repository/webkit/trunk@205386 268f45cc-cd09-0410-ab3c-d52691b4dbfc