[iOS] Remove unused variable from TileGrid::dropTilesBetweenRects()
Fixes the following build error:

    WebCore/platform/ios/TileGrid.mm:88:23: error: unused variable 'end' [-Werror,-Wunused-variable]
        TileMap::iterator end = m_tiles.end();
                          ^

* platform/ios/TileGrid.mm:
(WebCore::TileGrid::dropTilesBetweenRects): Remove unused
variable now that the for loop uses an auto iterator.

git-svn-id: https://svn.webkit.org/repository/webkit/trunk@161690 268f45cc-cd09-0410-ab3c-d52691b4dbfc